name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 4.0.3
api: 5.0.0
author: brokiem

website: https://github.com/brokiem/SimpleNPC

permissions:
  simplenpc.command:
    default: op
  simplenpc.rca:
    default: op
