name: SimpleNPC
main: brokiem\snpc\SimpleNPC
version: 4.0.4
api: 5.0.0
author:
  - brokiem
  - Blackjack200

website: https://github.com/Blackjack200/SimpleNPC

permissions:
  simplenpc.command:
    default: op
  simplenpc.rca:
    default: op
  simplenpc.list:
    default: op
